import control as ctrl
import tools as tool
import time

class Processor:
    def __init__(self, number, memory, instructionsHolder, l1cachedataholder, mutex, generator):
        self.number = number
        self.control = ctrl.Control(l1cachedataholder, memory, instructionsHolder)
        self.instrData = instructionsHolder
        self.memory = memory
        self.mutex = mutex
        self.generator = generator

        self.getAutoGeneratedInstructionDictionary = {
            0: self.instrData.getAutoGeneratedInstruction0,
            1: self.instrData.getAutoGeneratedInstruction1,
            2: self.instrData.getAutoGeneratedInstruction2,
            3: self.instrData.getAutoGeneratedInstruction3
        }
                                              
        self.setAutoGeneratedInstructionDictionary = {
            0: self.instrData.setAutoGeneratedInstruction0,
            1: self.instrData.setAutoGeneratedInstruction1,
            2: self.instrData.setAutoGeneratedInstruction2,
            3: self.instrData.setAutoGeneratedInstruction3
        }

        self.getInstructionDictionary = {
            0: self.instrData.getInstruction0,
            1: self.instrData.getInstruction1,
            2: self.instrData.getInstruction2,
            3: self.instrData.getInstruction3
        }

        self.setInstructionDictionary = {
            0: self.instrData.setInstruction0,
            1: self.instrData.setInstruction1,
            2: self.instrData.setInstruction2,
            3: self.instrData.setInstruction3
        }
        self.setOldInstructionDictionary = {
            0: self.instrData.setOldInstruction0,
            1: self.instrData.setOldInstruction1,
            2: self.instrData.setOldInstruction2,
            3: self.instrData.setOldInstruction3
        }

        self.getInstructionReadDictionary = {
            0: self.instrData.getInstruction0Read,
            1: self.instrData.getInstruction1Read,
            2: self.instrData.getInstruction2Read,
            3: self.instrData.getInstruction3Read
        }                                      
        self.setInstructionReadDictionary = {
            0: self.instrData.setInstruction0Read,
            1: self.instrData.setInstruction1Read,
            2: self.instrData.setInstruction2Read,
            3: self.instrData.setInstruction3Read
        }

    def getNumber(self):
        return self.number

    def setNumber(self, number):
        self.number = number
        return

    def readOperation(self):
        while (True):
            state = self.getInstructionReadDictionary.get(self.number)()
            auto = self.getAutoGeneratedInstructionDictionary.get(self.number)()
            if auto:
                instr = self.generator.generateInstructionFromProcessor(self.number)
                self.setInstructionDictionary.get(self.number)(instr)
                self.setAutoGeneratedInstructionDictionary.get(self.number)(0)

            if not (state):
                if not (auto):
                    instr = self.getInstructionDictionary.get(self.number)()

                wait = round(self.instrData.getInstructionTime() / 2)
                if (instr[:5] == "write"):
                    address = tool.binaryToDecimal(instr[6:9])
                    data = tool.hexadecimalToDecimal(instr[10:14])
                    if (address != -1 and data != -1):
                        print("P" + str(self.number) + ": Intruction to execute: " + instr + "\n")
                        time.sleep(wait)
                        self.mutex.acquire()
                        self.control.handleOperation("W", self.number, address, data)
                        self.mutex.release()
                        time.sleep(wait)
                        self.setInstructionDictionary.get(self.number)("")
                        self.setOldInstructionDictionary.get(self.number)(instr)
                        print("P" + str(self.number) + ": Executed instruction\n")
                    self.setInstructionReadDictionary.get(self.number)(1)
                elif (instr[:4] == "read"):
                    address = tool.binaryToDecimal(instr[5:8])
                    if (address != -1): 
                        print("P" + str(self.number) + ": Intruction to execute: " + instr + "\n")   
                        time.sleep(wait)
                        self.mutex.acquire()
                        self.control.handleOperation("R", self.number, address, -1)
                        self.mutex.release()
                        time.sleep(wait)
                        self.setInstructionDictionary.get(self.number)("")
                        self.setOldInstructionDictionary.get(self.number)(instr)
                        print("P" + str(self.number) + ": Executed instruction\n")
                    self.setInstructionReadDictionary.get(self.number)(1)
                elif (instr[:4] == "calc"):
                    print("P" + str(self.number) + ": Intruction to execute: " + instr + "\n")
                    time.sleep(wait)
                    time.sleep(wait)
                    self.setInstructionDictionary.get(self.number)("")
                    self.setOldInstructionDictionary.get(self.number)(instr)
                    print("P" + str(self.number) + ": Executed instruction\n")
                    self.setInstructionReadDictionary.get(self.number)(1)
                else:
                    print("P" + str(self.number) + ": Not a valid instuction, could not identify this op.\n")
                    self.setInstructionReadDictionary.get(self.number)(1)